apiVersion: v1
kind: Namespace
metadata:
  name: rs-app

---
# ===================================================================
#  1. CONFIGURATION & SECRETS
# ===================================================================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rs-app
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password123"
  POSTGRES_DB: "rs_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: rs-app
data:
  PGHOST: "db-svc"
  PGUSER: "admin"
  PGDATABASE: "rs_db"
  PGPORT: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: rs-app
type: Opaque
stringData:
  PGPASSWORD: "password123"

---
# ===================================================================
#  2. DATABASE LAYER (PostgreSQL)
# ===================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: rs-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: rs-app
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: Recreate # Diperlukan untuk volume ReadWriteOnce
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          # Probe Kesehatan Database
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "admin"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "admin"]
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: rs-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
# ===================================================================
#  3. BACKEND LAYER
# ===================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: rs-app
  labels:
    app: backend
spec:
  replicas: 3
  # Strategi Zero Downtime
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: daffamusyafa/rs-app-be:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          # Probe Kesehatan Backend
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: rs-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
# ===================================================================
#  4. FRONTEND LAYER
# ===================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: rs-app
  labels:
    app: frontend
spec:
  replicas: 4
  # Strategi Zero Downtime
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: daffamusyafa/oc-fe:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # Probe Kesehatan Frontend
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: rs-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
